apiVersion: v1
kind: Service
metadata:
  name: app-endpoint
  labels:
    app: event-app-endpoint
spec:
  selector:
    app: event-app-endpoint
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-app-endpoint
  labels:
    app: event-app-endpoint
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: event-app-endpoint
  template:
    metadata:
      labels:
        app: event-app-endpoint
    spec:
      containers:
      - name: event-app-endpoint
        image: event-app-endpoint:1.0.0-beta1
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: app-endpoint-config
              key: api_url
        - name: PUBLIC_TOKEN
          valueFrom:
            configMapKeyRef:
              name: app-endpoint-config
              key: token
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-endpoint-config
              key: mongodb_uri
