apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: event-api
spec:
  selector:
    app: event-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-api
  labels:
    app: event-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-api
  template:
    metadata:
      labels:
        app: event-api
    spec:
      containers:
      - name: event-api
        image: event-api:1.0.2
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: mongodb_uri
